// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Paschoalotto.Infrastructure;

namespace Paschoalotto.Migrations
{
    [DbContext(typeof(ApplicationDataContext))]
    partial class ApplicationDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Paschoalotto.Model.Debt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(17)")
                        .HasMaxLength(17);

                    b.Property<float>("FineFee")
                        .HasColumnType("real")
                        .IsUnicode(false);

                    b.Property<float>("Interest")
                        .HasColumnType("real")
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Debt","paschoalotto");
                });

            modelBuilder.Entity("Paschoalotto.Model.DebtInstallments", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DebtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<float>("Price")
                        .HasColumnType("real")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("DebtId");

                    b.ToTable("DebtInstallments","paschoalotto");
                });

            modelBuilder.Entity("Paschoalotto.Model.DebtInstallments", b =>
                {
                    b.HasOne("Paschoalotto.Model.Debt", null)
                        .WithMany("debtInstallments")
                        .HasForeignKey("DebtId");
                });
#pragma warning restore 612, 618
        }
    }
}
